# Generated by Django 4.1 on 2022-09-07 05:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RHApp', '0002_idioma_delete_competencias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.TextField(max_length=200)),
                ('Nivel', models.CharField(max_length=15)),
                ('Fecha_Desde', models.DateField(null=True)),
                ('Fecha_Hasta', models.DateField(null=True)),
                ('Institucion', models.TextField(max_length=55, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.TextField(max_length=200)),
                ('Activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empresa', models.TextField(max_length=35)),
                ('PuestoOcupado', models.TextField(max_length=45)),
                ('Fecha_Desde', models.DateField(null=True)),
                ('Fecha_Hasta', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Puesto', models.TextField(max_length=50)),
                ('Riesgo', models.CharField(max_length=20)),
                ('SalarioMinimo', models.IntegerField(null=True)),
                ('SalarioMaximo', models.IntegerField(null=True)),
                ('Activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cedula', models.TextField(max_length=13, validators=[django.core.validators.RegexValidator(message='El formato de Cedula debe ser XXX-XXXXXXX-X (Solo numerico)', regex='^\\d{3}-\\d{7}-\\d{1}$')])),
                ('Nombre', models.TextField(max_length=25)),
                ('Fecha_Ingreso', models.DateField(null=True)),
                ('Departamento', models.TextField(max_length=30)),
                ('Activo', models.BooleanField()),
                ('Puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RHApp.puesto')),
            ],
        ),
        migrations.CreateModel(
            name='Candidatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cedula', models.TextField(max_length=13, validators=[django.core.validators.RegexValidator(message='El formato de Cedula debe ser XXX-XXXXXXX-X (Solo numerico)', regex='^\\d{3}-\\d{7}-\\d{1}$')])),
                ('Nombre', models.TextField(max_length=25)),
                ('Departamento', models.TextField(max_length=50)),
                ('RecomendadoPor', models.TextField(max_length=50)),
                ('CapacitacionesPrincipales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RHApp.capacitaciones')),
                ('CompetenciasPrincipales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RHApp.competencia')),
                ('Exp_Laboral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RHApp.experiencialaboral')),
                ('PuestoAspira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RHApp.puesto')),
            ],
        ),
    ]
