# Generated by Django 4.1.1 on 2022-09-13 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RHApp', '0004_alter_idioma_idioma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatos',
            name='Cedula',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='El formato de Cedula debe ser XXX-XXXXXXX-X (Solo numerico)', regex='^\\d{3}-\\d{7}-\\d{1}$')]),
        ),
        migrations.AlterField(
            model_name='candidatos',
            name='Departamento',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='candidatos',
            name='Nombre',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='candidatos',
            name='RecomendadoPor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='capacitaciones',
            name='Descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='capacitaciones',
            name='Institucion',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='capacitaciones',
            name='Nivel',
            field=models.CharField(choices=[('Grado', 'Grado'), ('Post-Grado', 'Post-Grado'), ('Maestria', 'Maestria'), ('Doctorado', 'Doctorado'), ('Tecnico', 'Tecnico'), ('Gestion', 'Gestion')], default='Grado', max_length=15),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='Descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='Cedula',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='El formato de Cedula debe ser XXX-XXXXXXX-X (Solo numerico)', regex='^\\d{3}-\\d{7}-\\d{1}$')]),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='Departamento',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='Nombre',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='Puesto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='Riesgo',
            field=models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], max_length=20),
        ),
    ]
