# Generated by Django 4.1.1 on 2022-09-20 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RHApp', '0006_empleados_salariomensual'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatos',
            name='SalarioAspirado',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='Salario',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidatos',
            name='Cedula',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='capacitaciones',
            name='Nivel',
            field=models.CharField(choices=[('Grado', 'Grado'), ('Post-Grado', 'Post-Grado'), ('Maestria', 'Maestria'), ('Doctorado', 'Doctorado'), ('Tecnico', 'Tecnico'), ('Gestion', 'Gestion')], default='Grado', max_length=15),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='Cedula',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='Departamento',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='Nombre',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='SalarioMensual',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0, message='El salario debe ser mayor que cero')]),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='Empresa',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='PuestoOcupado',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='Puesto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='Riesgo',
            field=models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='SalarioMaximo',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='SalarioMinimo',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
