# Generated by Django 4.1 on 2022-09-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RHApp', '0008_alter_competencia_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatos',
            name='CapacitacionesPrincipales',
        ),
        migrations.AddField(
            model_name='candidatos',
            name='CapacitacionesPrincipales',
            field=models.ManyToManyField(to='RHApp.capacitaciones'),
        ),
    ]
