# Generated by Django 4.1.1 on 2022-09-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RHApp', '0012_alter_experiencialaboral_fecha_desde_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatos',
            name='CapacitacionesPrincipales',
        ),
        migrations.AddField(
            model_name='candidatos',
            name='CapacitacionesPrincipales',
            field=models.ManyToManyField(to='RHApp.capacitaciones'),
        ),
    ]
