# Generated by Django 4.1 on 2022-09-28 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RHApp', '0009_remove_candidatos_capacitacionesprincipales_and_more'),
        ('RHApp', '0014_remove_candidatos_competenciasprincipales_and_more'),
    ]

    operations = [
    ]
